# 机场订阅
proxy-providers:
  Pander:
    url: "机场订阅"   # clash 订阅链接
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连节点
    header:
      User-Agent:
      - "Clash"
      - "mihomo"
      - "Clash.meta"
    override:
      udp: true
      skip-cert-verify: true
#https://gh-proxy.com/raw.githubusercontent.com

# 节点信息
proxies:
  - {name: 直连节点, type: direct, udp: true}

# 全局配置 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
mode: rule
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true


# 控制面板
external-controller: 0.0.0.0:9090
secret: "dylan1010"
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# 嗅探  作用不是很大 在路由规则匹配的时候 如果是IP 通过嗅探匹配出对应 IP 的域名
sniffer:
  enable: true
  sniff:
    # HTTP TLS QUIC 嗅探的端口
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "rule-set:private_domain,cn_domain"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    - "+.wechat.com"
    - "+.qpic.cn"
    - "+.qq.com"
    - "+.wechatapp.com"
    - "+.vivox.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"

# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "time.*.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.pool.ntp.org"
    - "+.cn.ntp.org.cn"
  default-nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 221.5.203.98
    - 223.5.5.5
    - 119.29.29.29
 
# 出站策略
# 注意锚点必须放在引用的上方,可以集中把锚点全部放yaml的顶部。
# type:选择节点的类型；include-all:包含所有的机场的订阅链接（use:机场名）;tolerance:, interval:测速的间隔
proxymain: &proxymain {type: select, proxies: [🇭🇰 香港自动, 🇨🇳 台湾自动, 🇯🇵 日本自动, 🇸🇬 狮城自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点, 🚥 直连访问]}
directmain: &directmain {type: select, proxies: [🚥 直连访问, 🇭🇰 香港自动, 🇨🇳 台湾自动, 🇯🇵 日本自动, 🇸🇬 狮城自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点]}
proxy-groups:
  - {name: 🪜 翻墙代理, <<: *proxymain}
  - {name: 🍎 Apple, <<: *directmain}
  - {name: 🍎 ApplePro, <<: *proxymain}
  - {name: 🔍 Google, <<: *proxymain}
  - {name: Ⓜ️ Microsoft, <<: *proxymain}
  - {name: ☁️ OneDrive, <<: *directmain}
  - {name: 🐙 Develop, <<: *proxymain}
  - {name: 🤖 Intelligence, type: select, proxies: [🇯🇵 日本自动, 🇺🇸 美国自动]}
  - {name: 💰 Wallet, type: select, proxies: [🇨🇳 台湾自动, 🚥 直连访问, 🇭🇰 香港自动, 🇯🇵 日本自动, 🇸🇬 狮城自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点]}
  - {name: 🧭 Speedtest, <<: *directmain}
  - {name: 📱 Telegram, type: select, proxies: [🇸🇬 狮城自动, 🇭🇰 香港自动, 🇨🇳 台湾自动, 🇯🇵 日本自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点]}
  - {name: 🎸 Spotify, type: select, proxies: [🇨🇳 台湾自动, 🚥 直连访问, 🇭🇰 香港自动, 🇯🇵 日本自动, 🇸🇬 狮城自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点]}
  - {name: 📽️ 国外流媒体, type: select, proxies: [📺 流媒自动, 直连节点]}
  - {name: 🎵 TikTok, type: select, proxies: [🇺🇸 美国自动, 直连节点]}
  - {name: 🎮 游戏直连, <<: *directmain}
  - {name: 🎮 游戏代理, <<: *proxymain}
  - {name: 🚥 直连访问, type: select, proxies: [直连节点, 🇭🇰 香港自动, 🇨🇳 台湾自动, 🇯🇵 日本自动, 🇸🇬 狮城自动, 🇺🇸 美国自动, 🗺 环球节点, 🚀 全部节点]}
  - {name: 🐠 漏网之鱼, <<: *proxymain}

  - {name: 🇭🇰 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(福利|301|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 🇯🇵 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日本|🇯🇵))^((?!(福利|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 🇸🇬 狮城自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(新加坡|🇸🇬))^((?!(福利|301|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 🇨🇳 台湾自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(台湾|🇹🇼))^((?!(福利|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 🇺🇸 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美国|🇺🇸))^((?!(福利|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 📺 流媒自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(NF|Disney|HBO|Hulu))^((?!(福利|0.1x|0.2x|0.3x|0.4x|0.5x|0.6x|0.7x|0.8x|0.9x|3x|4x|5x)).)*$"}
  - {name: 🗺 环球节点, type: select, include-all: true, filter: "^((?!(香港|HK|Hong Kong|🇭🇰|HongKong|日本|🇯🇵|新加坡|🇸🇬|台湾|🇹🇼|美国|🇺🇸|福利|新用户|直连)).)*$"}
  - {name: 🚀 全部节点, type: select, include-all: true}

# 规则匹配 此规则部分没有做防泄露处理,因为弊严重大于利！注意顺序
rules:
  - RULE-SET,private_domain,🚥 直连访问
  - RULE-SET,per_direct,🚥 直连访问
  - RULE-SET,per_proxy,🪜 翻墙代理

  - RULE-SET,category_ai_chat_notcn_domain,🤖 Intelligence
  - RULE-SET,per_proxy_intelligence,🤖 Intelligence

  - RULE-SET,category_dev_domain,🐙 Develop
  - RULE-SET,developer_domain,🐙 Develop
  - RULE-SET,linux_domain,🐙 Develop
  - RULE-SET,per_proxy_develop,🐙 Develop

  - RULE-SET,onedrive_domain,☁️ OneDrive
  - RULE-SET,synology_domain,🚥 直连访问
  - RULE-SET,telegram_domain,📱 Telegram
  - RULE-SET,paypal_domain,💰 Wallet
  - RULE-SET,speedtest_domain,🧭 Speedtest

  - RULE-SET,spotify_domain,🎸 Spotify
  - RULE-SET,tiktok_domain,🎵 TikTok

  - RULE-SET,per_proxy_media,📽️ 国外流媒体
  - RULE-SET,globalmedia_domain,📽️ 国外流媒体
  - RULE-SET,category_media_domain,📽️ 国外流媒体
  - RULE-SET,category_media_cn_domain,🚥 直连访问
  - RULE-SET,chinamedia_domain,🚥 直连访问

  - RULE-SET,gamedownloadcn_domain,🎮 游戏直连
  - RULE-SET,category_games_cn_domain,🎮 游戏直连
  - RULE-SET,gamedownload_domain,🎮 游戏代理
  - RULE-SET,category_games_domain,🎮 游戏代理

  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,apple_notcn_domain,🍎 ApplePr
  - RULE-SET,google_domain,🔍 Google
  - RULE-SET,microsoft_domain,Ⓜ️ Microsoft

  - RULE-SET,proxy_domain,🪜 翻墙代理
  - RULE-SET,gfw_domain,🪜 翻墙代理
  - RULE-SET,geolocation_notcn_domain,🪜 翻墙代理
  - RULE-SET,cn_domain,🚥 直连访问

  - RULE-SET,per_proxy_develop_ip,🐙 Develop,no-resolve
  - RULE-SET,telegram_ip,📱 Telegram,no-resolve
  - RULE-SET,globalmedia_ip,📽️ 国外流媒体,no-resolve
  - RULE-SET,chinamedia_ip,🚥 直连访问,no-resolve
  - RULE-SET,google_ip,🔍 Google,no-resolve
  - RULE-SET,apple_ip,🍎 Apple,no-resolve
  - RULE-SET,cn_ip,🚥 直连访问
  - MATCH,🐠 漏网之鱼

#  - DOMAIN-SUFFIX,qichiyu.com,🚀 默认代理    # 临时添加规则


# 规则集
rule-anchor:    # 规则集的锚点
  # 锚点名字：&锚点名字{type:定义从哪里获取(http是网上,flie是本地), interval:更新时间, behavior:规则集内容是什么格式的(规则集中是IP(ipcidr)还是域名(domain)还是老格式(classical)),format:定义文件是什么格式}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
rule-providers:
  # 本地局域网
  private_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  # ai
  category_ai_chat_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-chat-!cn.mrs"}
  # 开发
  category_dev_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-dev.mrs"}
  developer_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Developer/Developer_OCD_Domain.mrs"}
  linux_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/linux.mrs"}
  # google
  google_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  google_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  # 微软
  onedrive_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  # 苹果
  apple_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple%40cn.mrs"}
  apple_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  apple_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
  # 金融
  paypal_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  # telegram
  telegram_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  telegram_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  # 媒体
  spotify_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}
  tiktok_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}

  globalmedia_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs"}
  globalmedia_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_IP.mrs"}
  category_media_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media.mrs"}

  category_media_cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media-cn.mrs"}
  chinamedia_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_Domain.mrs"}
  chinamedia_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_IP.mrs"}

  # 工具
  speedtest_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/speedtest.mrs"}
  synology_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/synology.mrs"}
  # 游戏
  gamedownloadcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN_OCD_Domain.mrs"}
  category_games_cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games%40cn.mrs"}
  gamedownload_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Game/GameDownload/GameDownload_OCD_Domain.mrs"}
  category_games_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs"}
  # 全局
  proxy_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/proxy.mrs"}
  gfw_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation_notcn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  cn_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  
  # 个人
  per_proxy_develop_ip: { <<: *ip, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Develop-IP.mrs"}
  per_direct: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Direct.mrs"}
  per_proxy_develop: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Develop.mrs"}
  per_proxy_intelligence: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Intelligence.mrs"}
  per_proxy_media: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy-Media.mrs"}
  per_proxy: { <<: *domain, url: "https://gh-proxy.com/raw.githubusercontent.com/SlippinDylan/mihomoRules/master/MRS/mrs/Proxy.mrs"}